-- 데이터베이스 CORRUPT됬을때 리셋용 스크립트
USE MELON;

-- 내용물 삭제
DELETE FROM SINGER;
DELETE FROM COMPANY;
DELETE FROM SONG;
DELETE FROM SONG_SINGER;
DELETE FROM ALBUM;
DELETE FROM ALBUM_SINGER;
DELETE FROM ALBUM_SONG;
DELETE FROM YEAR_CHART;
DELETE FROM TEN_YEARS_CHART;

